### ISSUE TITLE
Hello, the SourceCode just has jpgs, so i can't get code. 

### ISSUE THREAD

**Issue by juice77ooO** [ilie321/thermal-cam-android-for-purethermal-1#1]
Can you send sourcecode about apk for me? Thank you.

**Comment by theonlycolm** [comment]
Hi @ilie321 - thank you for your work on this app. I've been searching for one that works on Android for a while. Yours works perfectly on my OnePlus 12R!
Is it possible for me to have access to the sources for the app please? I'd like to add a 'flip image vertical' option and maybe a full screen landscape option also.

**Comment by ilie321** [comment]
Hello the source it a mess and very big idk if it will help for the moment. I updated app see if is ok now
